// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANCWpQRD4vDbJe46RVle_8kHPM3JJE_sQ',
    appId: '1:496178393403:web:6cd880a8eaf9780ab3c71e',
    messagingSenderId: '496178393403',
    projectId: 'plug-point-39517',
    authDomain: 'plug-point-39517.firebaseapp.com',
    storageBucket: 'plug-point-39517.firebasestorage.app',
    measurementId: 'G-J1GWDGY569',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv0TiiB7omt1DrdM4ztyS1rQELYDJWfnA',
    appId: '1:496178393403:android:ebf4204d751c0314b3c71e',
    messagingSenderId: '496178393403',
    projectId: 'plug-point-39517',
    storageBucket: 'plug-point-39517.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI5tzeynXRZXwbS37gWeS_VFNj0b8eWGk',
    appId: '1:496178393403:ios:c1999a00133acf87b3c71e',
    messagingSenderId: '496178393403',
    projectId: 'plug-point-39517',
    storageBucket: 'plug-point-39517.firebasestorage.app',
    iosBundleId: 'com.example.plugPoint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI5tzeynXRZXwbS37gWeS_VFNj0b8eWGk',
    appId: '1:496178393403:ios:c1999a00133acf87b3c71e',
    messagingSenderId: '496178393403',
    projectId: 'plug-point-39517',
    storageBucket: 'plug-point-39517.firebasestorage.app',
    iosBundleId: 'com.example.plugPoint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANCWpQRD4vDbJe46RVle_8kHPM3JJE_sQ',
    appId: '1:496178393403:web:1e9d746e3e46a4b5b3c71e',
    messagingSenderId: '496178393403',
    projectId: 'plug-point-39517',
    authDomain: 'plug-point-39517.firebaseapp.com',
    storageBucket: 'plug-point-39517.firebasestorage.app',
    measurementId: 'G-24HVC1ZP9S',
  );
}
